name: scamdonation
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - datasets=2.19.2
  - hdbscan=0.8.36
  - huggingface_hub=0.23.3
  - matplotlib-base=3.8.4
  - numba=0.59.1
  - numpy=1.26.4
  - pandas=2.2.2
  - pip=24.0
  - python=3.12.3
  - pytorch=2.3.1
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - tokenizers=0.19.1
  - torchvision=0.18.1
  - tqdm=4.66.4
  - transformers=4.41.2
  - umap-learn=0.5.5